### PR TITLE
Seems to be working to parse GPS out of EXIF data within image.

### PR DESCRIPTION
**Pull request by j-calvert**
The relevant changes are lines 21-32 of drag-and-drop.js

The GPS coordinates seem correct, but after about 5 minutes, the 360 photo is still not showing up on Google Maps.  Will check back in a bit.

image

Re: lot's of whitespace/formatting changes, open to recommendations.  I'm using Visual Studio Code.  Is there a formatting template I should be using.

### CODE REVIEW

**Comment by moom0o** [comment]
You'll probably have to wait closer to 30 minutes and then refresh, still doesn't work? Then try incognito mode or another browser.

**Comment by j-calvert** [comment]
Now the 360 is good, but the location is not.  Will keep checking back.

**Comment by j-calvert** [comment]
So weird, I was pretty sure the location was working as I had it, but it seems I needed a negative sign for longitude.

**Comment by j-calvert** [comment]
Yup, it's working now (gets GPS coords from EXIF metadata).

[My most recent pix](https://www.google.com/maps/contrib/104170287590632615529/photos/@19.1963806,-69.3322333,3a,75y,198.42h,100.12t/data=!3m7!1e1!3m5!1sAF1QipM76aOODWiKL2HZwxfHNoWUM699HshQEMXKMXtz!2e10!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipM76aOODWiKL2HZwxfHNoWUM699HshQEMXKMXtz%3Dw365-h260-k-no-pi-20.11257-ya179.88744-ro0-fo100!7i6080!8i3040!4m3!8m2!3m1!1e1) with "Unknown Location" added using the tool.

**Comment by moom0o** [comment]
For the negative long coordinate, what happens if its in the east where its positive?

**Comment by j-calvert** [comment]
> For the negative long coordinate, what happens if its in the east where its positive? (Same for lat)

You're right!  My laziness/sloppiness was showing 😄 

Lifted (now) from https://medium.com/spatial-data-science/how-to-extract-gps-coordinates-from-images-in-python-e66e542af354

**Comment by moom0o** [comment]
Hi @j-calvert, could you possibly add a way to write exif data? It would be very useful for images that don't have the required metadata by Google, such as drone panoramas.

You can find the required metadata here: https://developers.google.com/streetview/spherical-metadata

Thanks

**Comment by j-calvert** [comment]
> Hi @j-calvert, could you possibly add a way to write exif data? It would be very useful for images that don't have the required metadata by Google, such as drone panoramas.

Not sure what the ask is, here.  What would be writing to exif?

**Pull request merged**
